services:
  client:
    build: ./client
    container_name: Levchuk_client
    environment:
      NODE_ENV: production
    env_file:
      - ./client/.env
    ports:
      - "3000:80"

  api:
    build: ./server
    container_name: Levchuk_server
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - "8248:${PORT}"

  db:
    image: postgres:latest
    container_name: Levchuk_postgres_db
    hostname: Levchuk_db
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 10s
    volumes:
      - ./.pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  db: null
